sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-045
env:
  global:
    -
      # LTD_AWS_ID
      secure: badlc2BMIaQ2hD4YvrOPx00vBijsk/NUnA27J8Thd7Ug2ll+XblVKXy4M311jWLHo1P5hhOquAVd/UY/cPNuFh2yeGxyU2Q8FcSD8XDvqKLVPh+mjD5k9Vm6n0pbkyGqX0Glf8wmXTj++ukO/vvEvg3sM8Q13rOP8J1G+WNaqEvIUWnfaYpD08uPNOI35GnkeTo8x2Z36ANeHixUxSkiqpUNyhOhvNR5bbfOY5d76pitEGUDkQOa2/pRAJ9Ah8wC4HFrXG17JK1FEbGcJp6TuS9cnRMHg8oNAlZUMF+/+LjZqNh0qK6ux1gIbUWE9PTF23lKIgwk9XJfZMu5TjII5HWrELIKzmngz3XvbrutEm3KJMLFXxiPgqjvPs/zI17WVdOH4L8rF85o4yNCF9zlw4aQgTiu6Z0Ez+3ufDEmbJBsrD8btowlaQ+v8qmFlmT56ZEu5iT0lyn73Xzsk1o1DAmH4AVmzfbvVi/vc9BDl3loNcm43/tycE1kRPSmCUu2dZM4+ejckjNJqAEMgCIUTWts0K/9HV9/J0jNKKiOWQ+1WotSFWDiro4jL9OHrHEF2zSouzFryhKi9FRDd05r7k8XQ+S//WXPvFzrPfle1zYUm8WrGkG1SceGRX9UG4+HRBpReFckJERRewcIuEPn9fsm4S7UEmJM7uD0ek8NKis=
    -
      # LTD_AWS_SECRET
      secure: SO0f67gdBdwsnD5Gj5rQ9JM3c0nS9F1yILwEa1NWH+YjDM7wgMYTJFueRhLtyuAMO5WMBDmHV3llwmUnUnhbu5U6C86A0FJep+vNx5TXBeFCmARfqQk5b+JJB0iL3BGjWGvyO78NdwaY42dc/9oie0qltfOdYnh9J5MxrlDA25Zf63EuMok0Vewd0mm4pK8wzzXzzjePjw/f2bqOJPlJXtLvnVZL9V0zJZrcdpt/xy8YbEvHOK5PxGB5bJhE0H9NsC5BLTk7bvHoqLd3HPYVLJnaSQglTGK7wTZD2nQ4VXker+hEHG8jHAZrUX/BWF8KtUGj4J94Yu7aTWEk9kKH/lhF7C8tR7MognzOo3rHNY8oBq+JMCHlKnRtfBQ8S65CyYioDxwhxme8WAcMDBoQBJFrKb6Z+p6HgseNmxCcgaQr2iXEWTxCOOqgvKZfW0pL/MD8DlGiq1hmdeWg50JyR1UD0wBdQV9o36L9cUfbyhcjQRWw4JyQneTrkpuYTDyBayNXNHrVWdfZ9uPtYJaxnfqOh92ESLIIaYwkBJmsh4+EGL2gV6HfhKBJ9PJBgetRnKdz4+s59CMDElPgPuhwg6dbt90KXEQcJqseeVnY3qPooU/1oWRHSrfpPApR9guOGCWTNWRkiBHKYMlY5Bv5sa8URKmoDeZwU4W/MgSWePg=
    -
      # LTD_USERNAME
      secure: ZewvuPB4eiKGFxJ3SjSNikUch+27D73idrAzFvriNGakVBzT1/CZEggospJz06pbohnjIu0e0EOcHPC+7rST/8Y/afhfv23g+vcWHKLXpJGlqsi5S5fniJo5WtnKdgcuDJUSjMhtbgy9dTVuNtZ1qK/x87DMt92lVlhNlH6NssQErwRSwnF8W5pWIW+/tPqc+VMbRofgheEW/4odFK9yTc5R3xWi+iympTrXQKJ/4GpiuDMVBoLSfsytCdKmBSJ9NlqCpPo6+BDLnKbKvx6wy3/KwmDcn7JZMqQR7uQ/ttYsQvjdmMT64tX0vJJp/L9Webvydn+db8Emv1KzKzd/Ouc028mFMv/iuZww/DDZ25f0+opnGsTwh+M2xOWKW5BzglRjD7/fxVu7tBF4j1XqTAiXsrLC3/3nwW9rZ0CIEAiCPnQxgjyE4Aec/iS7Ml5dNZt8Row40OU0nA5UFGDdLQ9zvlUCE3KCpklFJuAh5d85mUjqRg4kEP6lF7ttqKkNuxtlRx18ppsytFDsBnGna3JlieXDhcwvBa3cHzNKuNCV1eO2343DQMNtw61iUMj6lOUCLhGbdWwc9ZMYB4nEEM2slh15EsiTk9YC3XX5eBXPOwRevX27BpXI0CKECOdNpfdPJFKZHxuiPOdhyoKnLTaR4rRkhNlzskgsefeDfMA=
    -
      # LTD_PASSWORD
      secure: GhK1TGmy+dTJGF/whjqZ1abyp4mkub0iYcPDCZWb0gic+n6VR8qZY7oU06+H/HInZqX4oX+p0u+uLtwoWl7EzRwjiTeEz1wQHur8fqG4LjXLL4vsmdbgHDDOHXwHSBE/6QK2i66PrWPvmLRmHFUB1iMYRvH7dBwbyptq53xSRQgmNNniQawi7ZByf+cj7W70kG0keAIQaOOdj7iCWAg39c/kNpi9zHV6peGHSt4ZS14nejvG5A9JfJ8/wduPqMXG+HUhr1V0ce7DN+Zg8XKKfGEVPSH67zAmoSZM22tQiNeHx+RoZkee5et7kJEMB7l70ras08qPyHBcHRuiRKxAX/QlsRgTcF/OS3qOxc2+X288vuaGAaZwDE/+1N3S5ddANLEzMVuzfNAcB3u82XLnQ+x1+khvB/rauULSczkbz3rw5up7W720QIru9BiqH6+jrOW9PWLOCC2ytTJMH9zyo9KYokJzmxn5UCDFJzbynsRmHcl81yBpG2/unuMdk1TA7QV34q6LAyzVWs880CWimAJ7d8vZ6kXrikvXtvsPoC+JXzFe2n4RYqbdgxaT9TFlREDDFUmfVzcKIVkcGOu/WAlLLtpIP/pM87TXW2ZvtuuzSUptKTR+PgtTrSUhJdoaMvg/G3aBu2qcFzPN7HVo1A65Fgg/nQinpS9dlOdnjZ8=
